name: 01 - Building Blocks
on: 
  - workflow_dispatch

jobs:

  echo-hello:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Hello, World!"
  echo-goodbye:
    runs-on: ubuntu-latest
    steps:
      - name: non-failing step
        run: |
          echo "I will fail"
          exit 0
      - name: Say goodbye
        run: echo "Goodbye!"