name: 07 - Using Expressions

on:
    push:
    workflow_dispatch:
        inputs:
            debug:
                type: boolean
                default: false

jobs:
    echo:
        runs-on: ubuntu-latest
        steps:
            -   name: Print start-up data
                if: ${{inputs.debug}} == true
                run: |
                    echo "Triggered by: ${{github.event_name}}"
                    echo "Branch: ${{github.ref}}"
                    echo "Commit SHA: ${{github.sha}}"
                    echo "Runner OS: ${{runner.os}}"
                    echo "Runner Architecture: ${{runner.arch}}"
                    echo "Runner Temp: ${{runner.temp}}"
                    echo "Runner tool cache: ${{runner.tool_cache}}"


